name: testing on opend PR to main
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
# defined jobs
jobs:
  # job name
  before-check:
    # runnner
    runs-on: ubuntu-latest
    # run commands
    steps:
      # clone repository
      - uses: actions/checkout@v2
      - name: fail case
        if: startsWith(github.head_ref, 'refs/heads/test/') && github.base_ref == refs/heads/main'
        run: exit 1
      - name: success case
        run: echo "OK"
  exec-test:
    # runnner
    runs-on: ubuntu-latest
    # run commands
    steps:
      - name: TEST!
        run: echo "RUN TEST
