name: testing on PR to main
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
jobs:
  validate-npm-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://registry.npmjs.org'
      - name: can npm publish?
        run: npx can-npm-publish
  basics-testing-on-ubuntu:
    needs:
      - validate-npm-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://registry.npmjs.org'
      - name: npm continuous install
        run: npm ci
      - name: git configure
        run: |
          git config --global user.email test@example.com
          git config --global user.name test
      - name: run testing
        run: npm run headless-test
      - name: run testing in docker-compose
        run: sh -c ./test-all.zsh
      - name: find sh
        run: cat ./test-all.zsh
  common-testing-on-windows:
    needs:
      - validate-npm-version
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - name: npm continuous install
        run: npm ci
      - name: git configure
        run: |
          git config --global user.email test@example.com
          git config --global user.name test
      - name: run testing
        run: npm run headless-test
