name: open PR to main
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
jobs:
  validate-npm-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: can npm publish?
        run: npx can-npm-publish
