name: npm publish after passing testing
on:
  push:
    branches:
      - master
# defined jobs
jobs:
  # job name
  npm-publish:
    # runnner
    runs-on: ubuntu-latest
    # run commands
    steps:
      # clone repository
      - uses: actions/checkout@v2
      # setup nodejs
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - name: run publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
